config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    invitations: 'users/invitations',
    confirmations: 'confirmations' }

  get 'pages/home'
  root 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :event_invitations, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy] do
    get :remove_photo, on: :member
  end

  resources :events do
    get :my, on: :collection
    get :remove_background_image, on: :member
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 8)
  end

  def show
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = "Reply sent"
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = "The conversation was moved to trash."
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = "The conversation was restored."
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = "Your trash was cleaned!"
    redirect_to conversations_path
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = "The conversation was marked as read."
    redirect_to conversations_path
  end

  private

  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = "inbox"
    end
    @box = params[:box]
  end

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, "")
    opts[:class] += " active" if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end 

  def bold_unread(conversation, user, box)
    conversation.is_unread?(user) && (box == "inbox") ? "bold-unread" : "readed"
  end

  def bold_box(active, box)
    active == box  ? "bold-unread" : "readed"
  end

  def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    current_user.mailbox.inbox(unread: true).count(:id, distinct: true) if current_user.mailbox
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
  <%= link_to conversation.subject, conversation_path(conversation), class: bold_unread(conversation, current_user, @box)   %>

  <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
      <p><%= link_to "Restore", restore_conversation_path(conversation), method: :post %></p>
    <% else %>
      <p><%= link_to "Move to trash", conversation_path(conversation), method: :delete,
                  data: {confirm: "Are you sure?"} %></p>
      <% if conversation.is_unread?(current_user) && @box == "inbox" %>
        <p><%= link_to "Mark as read", mark_as_read_conversation_path(conversation), method: :post %></p>
      <% end %>
    <% end %>
  </div>

  <p><%= render "conversations/participants", conversation: conversation %></p>
  <p><%= conversation.last_message.body %>
    <small>(<span class="text-muted"><%= conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></span>)</small>
  </p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>
  <% unless participant == current_user %>
    <%= image_tag participant.avatar, width: 30, title: participant.first_name, class: "img-rounded" %>
  <% end %>
<% end %>

app/views/conversations/index.html.erb
<div class="page-section colord text-center">
  <h2><%= "Your conversations (#{@box})" %></h2>
</div>
<section id="aboutUs">
  <div class="container">
    <div class="row feature design">
      <div class="col-sm-3">
        <ul class="nav">
          <%= mailbox_section "inbox", @box, class: bold_box("inbox", @box) %>
          <%= mailbox_section "sent", @box, class: bold_box("sent", @box) %>
          <%= mailbox_section "trash", @box, class: bold_box("trash", @box) %>
        </ul>
        <p class="start-conversation"><%= link_to "Start new conversation", new_message_path, class: "btn btn- btn-default" %></p>
      </div>
      <div class="col-sm-9">
        <% if @box == "trash" %>
          <p><%= link_to "Empty trash", empty_trash_conversations_path, method: :delete,
                         data: {confirm: "Are you sure?"} %></p>
        <% end %>
        <ul class="list-group">
          <%= render partial: "conversations/conversation", collection: @conversations %>
        </ul>
        <%= will_paginate %>
      </div>
    </div>
  </div>
</section>

app/views/conversations/show.html.erb
<div class="page-section colord text-center">
  <h2>Conversation</h2>
</div>
<section id="aboutUs">
  <div class="container">
    <div class="row feature design">
    <p>Chatting with
      <%= render "conversations/participants", conversation: @conversation %>
    </p>
    <div class="panel panel-default">
      <div class="panel-heading"><%= @conversation.subject %></div>
      <div class="panel-body">
        <div class="messages">
          <% @conversation.receipts_for(current_user).each do |receipt| %>
            <div class="media">
              <% message = receipt.message %>
              <div class="media-left">
                <%= image_tag message.sender.avatar, width: 30, title: message.sender.mailboxer_name, class: "img-rounded" %>
              </div>
              <div class="media-body">
                <h6 class="media-heading"><%= message.sender.mailboxer_name %>
                  says at <%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %></h6>
                <%= message.body %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= form_tag reply_conversation_path(@conversation), method: :post do %>
      <div class="form-group">
        <%= text_area_tag "body", nil, cols: 3, class: "form-control wow fadeInUp black_text", placeholder: "enter your message", required: true %>
      </div>
      <%= submit_tag "Send Your Reply", class: "btn btn-default" %>
    <% end %>
    </div>
  </div>
</section>