config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    invitations: 'users/invitations',
    confirmations: 'confirmations' }

  get 'pages/home'
  root 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :event_invitations, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy] do
    get :remove_photo, on: :member
  end

  resources :events do
    get :my, on: :collection
    get :remove_background_image, on: :member
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  username               :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  bio                    :text
#  age                    :integer
#  gender                 :string
#  first_name             :string
#  last_name              :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  invitation_token       :string
#  invitation_created_at  :datetime
#  invitation_sent_at     :datetime
#  invitation_accepted_at :datetime
#  invitation_limit       :integer
#  invited_by_id          :integer
#  invited_by_type        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :confirmable,
         :rememberable, :trackable, :validatable, :omniauthable, :invitable,
         omniauth_providers: [:facebook, :twitter]

  acts_as_messageable

  validates_presence_of :username
  validates_uniqueness_of :username

  validates :first_name, presence: true

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :invitations, dependent: :destroy, class_name: "User", as: :invited_by

  has_many :recieved_event_invitations, dependent: :destroy, class_name: "EventInvitation", foreign_key: "invitee_id"
  has_many :event_invitations, dependent: :destroy

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/gravatar.jpg"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes

  def request_friendship(user_2)
  	self.friendships.create(friend: user_2)
  end

  def pending_friend_requests_from
    self.inverse_friendships.where(state: "pending")
  end

  def pending_friend_requests_to
    self.friendships.where(state: "pending")
  end

  def active_friends
    self.friendships.where(state: "active").map(&:friend) + self.inverse_friendships.where(state: "active").map(&:user)
  end

  def friendship_status(user_2)
    friendship = Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id])
    unless friendship.any?
      return "not_friends"
    else
      if friendship.first.state == "active"
        return "friends"
      else
        if friendship.first.user == self
          return "pending"
        else
          return "requested"
        end
      end
    end
  end

  def friendship_relation(user_2)
    Friendship.where(user_id: [self.id,user_2.id], friend_id: [self.id,user_2.id]).first
  end

  def mailboxer_email(object)
    email
  end

  def mailboxer_name
    [first_name, last_name].compact.join(" ")
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_filter :configure_permitted_parameters, if: :devise_controller?

  def create
    params[:user][:username] = SecureRandom.urlsafe_base64(nil, false)
    super
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:accept_invitation) do |u|
      u.permit(:username, :first_name, :email, :password, :password_confirmation, :invitation_token)
    end
    devise_parameter_sanitizer.for(:invite).push(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only:[:index]
  before_action :set_user, only:[:show]
  before_action :get_counts, only: [:index]

  def index
    case params[:people] when "friends"
      @users = current_user.active_friends
    when "requests"
      @users = current_user.pending_friend_requests_from.map(&:user)
    when "pending"
      @users = current_user.pending_friend_requests_to.map(&:friend)
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  def show
    @post = Post.new
    @posts = @user.posts.order('created_at DESC')
    @activities = PublicActivity::Activity.where(owner_id: @user.id).order('created_at DESC')
  end

  private

  def get_counts
    @friend_count = current_user.active_friends.size
    @pending_count = current_user.pending_friend_requests_to.map(&:friend).size
  end

  def set_user
    @user = User.find_by(username: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
	def action_buttons(user)
		case current_user.friendship_status(user) when "friends"
			link_to "Cancel Friendship", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "pending"
			link_to "Cancel Request", friendship_path(current_user.friendship_relation(user)), method: :delete
		when "requested"
			link_to "Accept", accept_friendship_path(current_user.friendship_relation(user)), method: :put
		when "not_friends"
			link_to "Add as Friend", friendships_path(user_id: user.id), method: :post
		end
	end
end

app/views/users/_user.html.erb
<div class="col-md-3">
<div class="thumbnail">
<%= link_to user_path(user.username) do %>
  <%= image_tag user.avatar, width: 100 %>
<% end %>
<div class="caption">
<h3><%= "#{user.first_name} #{user.last_name}" %></h3>
<% if current_user %>
<p><%= action_buttons(user)%></p>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="page-section colord text-center">
  <h2>People</h2>
  <div class="btn-group" role="group" aria-label="Default">
    <%= link_to "Everyone", users_path, class: "btn btn-default #{'active' unless params[:people]}" %>
    <%= link_to "Friends (#{@friend_count})", users_path(people: "friends"), class: "btn btn-default #{'active' if params[:people] == 'friends'}" %>
    <%= link_to "Requests (#{request_count})", users_path(people: "requests"), class: "btn btn-default #{'active' if params[:people] == 'requests'}" %>
    <%= link_to "Pending (#{@pending_count})", users_path(people: "pending"), class: "btn btn-default #{'active' if params[:people] == 'pending'}" %>
  </div>
</div>
<section id="aboutUs">
  <div class="container">
    <div class="row feature design">
      <%= render @users %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">

      <div class="col-md-4">
        <%= image_tag @user.avatar, width: 200 %>
      </div>

      <div class="col-md-4">
        <h3><%= "#{@user.first_name} #{@user.last_name}" %></h3>
        <p>Age: <%= @user.age %></p>
        <p>Gender: <%= @user.gender %></p>
      </div>

      <div class="col-md-4">
        <h3>Who am I</h3>
        <small><%= @user.bio %></small>
        <% unless current_user == @user %>
          <%= link_to "Send a message to #{@user.mailboxer_name}", new_message_path(to: @user.id), class: 'btn btn-default btn-sm' %>
        <% end %>
      </div>

    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <!-- Friend Zone -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">Friends (<%= @user.active_friends.size %>)
        </div>
        <div class="panel-body">
          <% @user.active_friends.last(16).each do |user| %>
            <%= link_to user_path(user.username) do %>
              <%= gravatar_tag user.email, size: 40 %>
            <% end %>
          <% end %>
        </div>
      </div>
      <% if current_user && current_user == @user %>
        <p><%= link_to "Send invitation via email", new_user_invitation_path %><%= "   (#{@user.invitations.count} sent)" %></p>
        <button id="invitation_email" class="btn btn-default">Invite Facebook friends</button>
      <% end %>
    </div>
    <!-- Post Zone -->
    <div class="col-md-6">
      <% if current_user && current_user == @user %>
        <%= render "posts/form" %>
      <% end %>
      <%= render @posts %>
    </div>
    <!-- Profile Activity -->
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading">Recent Activity</div>
        <div class="panel-body">
          <%= render_activities(@activities) %>
        </div>
      </div>
    </div>
  </div>
</div>