config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    invitations: 'users/invitations',
    confirmations: 'confirmations' }

  get 'pages/home'
  root 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :event_invitations, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy] do
    get :remove_photo, on: :member
  end

  resources :events do
    get :my, on: :collection
    get :remove_background_image, on: :member
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                            :integer          not null, primary key
#  user_id                       :integer
#  description                   :text
#  description_html              :text
#  title                         :string
#  location                      :string
#  background_image_file_name    :string
#  background_image_content_type :string
#  background_image_file_size    :integer
#  background_image_updated_at   :datetime
#  start_at                      :datetime
#  end_at                        :datetime
#  private                       :boolean          default("f"), not null
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  latitude                      :float
#  longitude                     :float
#

class Event < ActiveRecord::Base
  attr_reader :remove_image

  geocoded_by :location
  after_validation :geocode, if: ->(obj) { obj.location.present? and obj.location_changed? }

  belongs_to :user
  has_many :event_invitations, dependent: :destroy

  validates_presence_of :user_id
  validates_presence_of :title

  has_attached_file :background_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/gravatar.jpg"

  validates_attachment_content_type :background_image, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :background_image, less_than: 2.megabytes

  auto_html_for :description do
    html_escape
    sized_image(width: "50%", height: "50%")
    youtube(width: "100%", height: 250, autoplay: false)
    link target: "_blank", rel: "nofollow"
    simple_format
  end

  class << self
    def accepted_by(user)
      joins(:event_invitations).where(event_invitations: { invitee_id: user.id, status: "accepted" }).uniq
    end

    def rejected_by(user)
      joins(:event_invitations).where(event_invitations: { invitee_id: user.id, status: "rejected" }).uniq
    end

    def not_replied_by(user)
      joins(:event_invitations).where(event_invitations: { invitee_id: user.id, status: "sent" }).uniq
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :show, :update, :destroy, :remove_background_image]

  def index
    current_user_id = current_user.try(:id)
    @page_header = "All events"
    @events = Event.where("user_id = ? OR private = ?", current_user_id, false)
                   .order(created_at: :desc)
                   .paginate(page: params[:page], per_page: 3)
    render :index
  end

  def my
    @new_count = Event.not_replied_by(current_user).count
    @rejected_count = Event.rejected_by(current_user).count
    @accepted_count = Event.accepted_by(current_user).count

    @page_header = "My events"

    case params[:specify_my_events]
    when "accepted"
      @events = Event.accepted_by(current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 3)
    when "rejected"
      @events = Event.rejected_by(current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 3)
    when "new"
      @events = Event.not_replied_by(current_user).order(created_at: :desc).paginate(page: params[:page], per_page: 3)
    else
      @events = Event.where(user_id: current_user.id).order(created_at: :desc).paginate(page: params[:page], per_page: 3)
    end

    render :index
  end

  def new
    @event = current_user.events.new
  end

  def create
    params[:event].delete(:background_image) if params[:event][:remove_image] != "1"
    @event = current_user.events.new(event_params)
    if @event.save
      redirect_to events_path, notice: "Event Created"
    else
      redirect_to :back, notice: @event.errors.full_messages.join(", ")
    end
  end

  def edit
  end

  def update
    params[:event].delete(:background_image) if params[:event][:remove_image] != "1"
    if @event.update(event_params)
      redirect_to events_path, notice: "Event Updated"
    else
      redirect_to :back, notice: @event.errors.full_messages.join(", ")
    end
  end

  def show
    @acceptable_link = Event.not_replied_by(current_user).include?(@event)
    @hash = Gmaps4rails.build_markers([@event]) do |event, marker|
      marker.lat event.latitude
      marker.lng event.longitude
      marker.infowindow "<b>#{event.title} at #{event.start_at}</b>"
    end
  end

  def destroy
  end

  def remove_background_image
    @notice = "event background_image has been removed" unless @event.background_image.blank?
    @event.background_image = nil
    @event.save
    redirect_to :back, notice: @notice
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :description, :private, :location, :start_at, :end_at, :background_image)
  end
end

app/views/events/_event.html.erb
<section id="contactUs" class="contact-parlex">
  <div class="parlex-back">
    <div class="container">
      <div class="row">
        <div class="heading text-center"> 
          <h2>Event details</h2>
        </div>
      </div>
      <div class="row mrgn30">
        <div id="contactfrm">
          <%= simple_form_for(@event, html: {class: "form-horizontal", id: "contact-form"}) do |f| %>
          <%= f.error_notification %>
            <div class="col-sm-12">
              <div class="form-group">
                <%= f.input :title, required: true, autofocus: true, label: false, placeholder: "Event title", input_html: { class: "form-control wow fadeInUp", id: "title"} %>
              </div>
              <div class="form-group">
                <%= f.input :location, required: false, label: false, placeholder: "Location", input_html: { class: "form-control wow fadeInUp", id: "Location"} %>
              </div>
              <div class="form-group">
                <%= f.input :start_at, required: false, label: "Starts", input_html: { class: "form-control wow fadeInUp", id: "Starts"} %>
              </div>
              <div class="form-group">
                <%= f.input :end_at, required: false, label: "Ends", input_html: { class: "form-control wow fadeInUp", id: "Ends"} %>
              </div>

              <div class="form-group">
                <%= image_tag @event.background_image, width: 50 unless @event.background_image.blank? %>
              </div>
              <div class="form-group">
                <%= f.input :background_image, as: :file %>
              </div>
              <div class="form-group">
                <%= f.input :remove_image, as: :boolean, required: false, label: "Save chosen background_image", input_html: { checked: true, class: "form-control wow fadeInUp", id: "remove_background_image"} %>
              </div>
              <% if @event.persisted? %>
                <%= link_to "Remove existing background_image", remove_background_image_event_path %>
              <% end %>     
              <div class="form-group">
                <%= f.input :description, required: true, label: "Event description", placeholder: "can add formatted text, links, video", input_html: { class: "form-control wow fadeInUp", id: "description"} %>
              </div>
              <div class="form-group">
                <%= f.input :private, required: false, label: "Private event", input_html: {class: "form-control wow fadeInUp", id: "private" } %>
              </div>          
              <div class="form-group">
                <%= f.button :submit, "Make event live!", class: "btn btn-success wow fadeInUp col-sm-12" %>
              </div>              
            </div>
          <% end %>
        </div>  
      </div>
    </div>
  </div>
</section>

app/views/events/edit.html.erb
  <%= render "event" %>

app/views/events/index.html.erb
<div class="page-section colord text-center">
  <h2><%= @page_header %></h2>
  <% if @page_header == "My events" %>
  <div class="btn-group" role="group" aria-label="Default">
    <%= link_to "Accepted (#{@accepted_count})", my_events_path(specify_my_events: "accepted"), class: "btn btn-default #{'active' if params[:specify_my_events] == 'accepted'}" %>
    <%= link_to "Rejected(#{@rejected_count})", my_events_path(specify_my_events: "rejected"), class: "btn btn-default #{'active' if params[:specify_my_events] == 'rejected'}" %>
    <%= link_to "New invitations (#{@new_count})", my_events_path(specify_my_events: "new"), class: "btn btn-default #{'active' if params[:specify_my_events] == 'new'}" %>
    <%= link_to "My events", my_events_path, class: "btn btn-default #{'active' unless params[:specify_my_events]}" %>
  </div>
  <% end %>
</div>
<section id="aboutUs">
  <div class="container">
    <div class="row feature design">
      <% @events.each_with_index do |event, index| %>
        <div class="event_preview">
          <%= image_tag event.background_image unless event.background_image.blank? %>
          <div class="text_on_image">
            <h4><%= link_to event.title, event_path(event) %></h4>
            <div class="event_preview_left"><%= raw(event.description_html) %></div>
            <div class="event_date_right">Time untill event <%=  distance_of_time_in_words(Time.now, event.start_at) %></div>
          </div>
        </div>
      <% end %>
      <div><%= will_paginate %></div>
    </div>
    <div class="button-right col-md-12"><%= button_to "Create event", new_event_path, method: "get", class: "btn btn-default" %></div>
  </div>
</section>

app/views/events/new.html.erb
  <%= render "event" %>

app/views/events/show.html.erb
<div class="page-section colord text-center">
  <h2><%= @event.title %></h2>
  <% if current_user == @event.user %>
  <div class="btn-group" role="group" aria-label="Default">
    <%= button_to "Edit event", edit_event_path(@event), method: "get", class: "btn btn-default" %>
  </div>
  <% end %>
</div>
<section id="aboutUs">
  <div class="container">
    <div class="row feature design">
      <div class="event_main">
        <div class="event_show">
          <%= image_tag @event.background_image unless @event.background_image.blank? %>
          <div class="text_on_image">
            <div class="event_location_up">
              <h4><%= @event.location %></h4>
              <div style='width: 300px;'>
                <div id="map" style='width: 300px; height: 200px;'></div>
              </div>
            </div>
            <div class="event_show_center"><%= raw(@event.description_html) %></div>
            <div class="event_date_right">Time untill event <%=  distance_of_time_in_words(Time.now, @event.start_at) %></div>
          </div>
        </div>
      </div>
      <div class="friends_invitations">
        <div class="col-md-6">
          <p>Attendees:</p>
          <% EventInvitation.accepted(@event).each do |invitation| %>
           <p><%= invitation.invitee.mailboxer_name%></p>
          <% end %>
        </div>
        <div class="col-md-6">
          <% if @acceptable_link %>
            <%= link_to "accept", accept_event_invitation_path, method: :put %>
            /
            <%= link_to "reject", reject_event_invitation_path, method: :put %>
          <% end %>
        </div>
      </div>
      <% if current_user == @event.user %>
        <%= form_tag event_invitations_path, method: :post do %>
          <div class="form-group">
            <%= label_tag "recipients", "Invite friends" %>
            <%= select_tag "recipients", invite_recipients_options(@chosen_recipient), multiple: true, class: "form-control chosen-it" %>
            <%= hidden_field_tag "event_id", @event.id %>
          </div>
          <%= submit_tag "Invite", class: "btn btn-default" %>
        <% end %>  
        <div class="sent_invitations">
          *Invitations have been sent to:
          <% @event.event_invitations.each do |invitation| %>
           <%= invitation.invitee.mailboxer_name %>, 
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</section>