config/routes.rb
Rails.application.routes.draw do

  get 'users/show'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
    invitations: 'users/invitations',
    confirmations: 'confirmations' }

  get 'pages/home'
  root 'pages#home'

  resources :users, only: [:show, :index]
  resources :friendships, only: [:create, :destroy, :accept] do
    member do
      put :accept
    end
  end

  resources :event_invitations, only: [:create] do
    member do
      put :accept
      put :reject
    end
  end

  resources :posts, only: [:create, :edit, :update, :destroy] do
    get :remove_photo, on: :member
  end

  resources :events do
    get :my, on: :collection
    get :remove_background_image, on: :member
  end

  resources :activities, only: [:index]

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  resources :messages, only: [:new, :create]

end

app/views/layouts/_header.html.erb
<nav id="mainNav">
  <div id="menuToggle"><i class="fa fa-bars"></i></div>
  <ul class="menuLinks">
    <% if current_user %>
        <li><%= link_to "Activities", activities_path %></li>
        <li><%= link_to "People (#{request_count})", users_path %></li>
        <li><%= link_to "Friends", users_path(people: "friends") %></li>
        <li><%= link_to "All Events", events_path %></li>
        <li><%= link_to "My Events", my_events_path %></li>
        <li><%= link_to "Conversations (#{unread_messages_count} unread)", conversations_path %></li>
        <li><%= link_to "Profile", user_path(current_user.username) %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Signup", new_user_registration_path %></li>
      <li><%= link_to "Login", new_user_session_path %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if IE 7 ]>    <html lang="en-gb" class="isie ie7 oldie no-js"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en-gb" class="isie ie8 oldie no-js"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en-gb" class="isie ie9 no-js"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en-gb" class="no-js">
<!--<![endif]-->
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<!--[if lt IE 9]> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
<title>Mycliq</title>
<meta name="description" content="">
<meta name="author" content="Mycliq">
<!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<!--[if lte IE 8]>
    <script type="text/javascript" src="http://explorercanvas.googlecode.com/svn/trunk/excanvas.js"></script>
  <![endif]-->
  <title>Mycliq</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<body>

<%= render "layouts/header" %>
<!--/.header-->
<% flash.each do |type, message| %>
  <div class="alert alert-default fade-in">
  <button class="close" data-dismiss="alert">x</button>
  <%= message %>
  </div>
<% end %>

<%= yield %>
<footer>
  <div class="container">
    <div class="social text-center"> <a href="#"><i class="fa fa-twitter"></i></a> <a href="#"><i class="fa fa-facebook"></i></a> <a href="#"><i class="fa fa-dribbble"></i></a> <a href="#"><i class="fa fa-flickr"></i></a> <a href="#"><i class="fa fa-github"></i></a> </div>
    <div class="clear"></div>
    <!--CLEAR FLOATS--> 
  </div>
</footer>
<!--/.page-section-->
<section class="copyright">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center"> Copyright 2016 | All Rights Reserved -- Mycliq</a> </div>
    </div>
    <!-- / .row --> 
  </div>
</section>

<!--[if lte IE 8]><script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script><![endif]--> 

<%= javascript_tag do %>
  $(document).ready(function() {
    $(document).on('click', '#menuToggle', function() {
      if ( $(this).find('i').hasClass('fa-bars') ) {
        $(this).find('i').removeClass('fa-bars').addClass('fa-remove');
        $('#mainNav').animate({"right":"0px"}, "slow");
      } else {
        $('#mainNav').animate({"right":"-200px"}, "slow");
        $(this).find('i').removeClass('fa-remove').addClass('fa-bars');
      }
    });
  });
<% end %>

<% if user_signed_in? %>
  <%= javascript_tag do %>
  $(document).ready(function() {

    $.ajaxSetup({ cache: true });
    $.getScript('//connect.facebook.net/en_US/sdk.js', function(){
      FB.init({
        appId: '493192404199133',
        version: 'v2.5'
      });
      $(document).on('click', '#invitation_email', function() {
        FB.ui({
        method: 'send',
        link: 'https://mycliq.herokuapp.com/',
        display: 'popup'
        },
        function(event) {
          var e = event
          if(e != null){
            $("body").prepend('<div class="alert alert-default fade-in"><button class="close" data-dismiss="alert">x</button>Facebook invitation has been sent.</div>');
          }
        });
      });
    });

    handler = Gmaps.build('Google');
      handler.buildMap({ provider: {zoomControl: true, mapTypeControl: false, streetViewControl: false}, internal: {id: 'map'}}, function(){
      markers = handler.addMarkers(<%=raw @hash.to_json %>);
      handler.bounds.extendWith(markers);
      handler.fitMapToBounds();
      handler.getMap().setZoom(14);
    });
  });
  <% end %>
<% end %>

</body>
</html>